### ISSUE TITLE
Replace baserow data with actual data 

### ISSUE THREAD

**Issue by thejoefriel** [wrkclasshistory/working-class-history#79]
**Summary**
We now have clean data to work with. We've just got 250 at this point so we can get a process in place for how we plan to add all the data to Baserow
[cleaned sample dataset.xlsx](https://github.com/yalla-coop/working-class-history/files/7784685/cleaned.sample.dataset.xlsx)

Can you have a think @fadeomar as to the best way to get this into the baserow set up? I'm assuming some sort of script, but also need to think about the best way of populating the tags table for example?

- [x] Think through best way to add initial data to Baserow (replacing the existing data on there)
- [x] Carry out the approach with this initial data so we can test it all works
- [x] Write the approach here as a comment so we have it for reference for when we look to add all 3000 rows of data

**Comment by thejoefriel** [comment]
Hi @fadeomar can't see any written approach on what you need WCH to do etc as requested. 

To help you out on this, here's a notion doc where I've basically done most of it for you. Can you please:

- Add further notes (i.e. issues we need to be aware of), steps on what needs to be done next etc that I haven't yet covered
- Add the spreadsheet templates
- Add the spreadsheet with the highlighted columns of where there were issues

**Comment by fadeomar** [comment]
**Add further notes**
  - the name of the columns must be the same because the code parsing depending on that.
  - the script convert data from CSV file so after done with entering data to excel sheet you must convert it to CSV file.
  - then upload the file to the input on page '/add-new-articles'. and will start post the articles 

**Add the spreadsheet templates**
[clean template.xlsx](https://github.com/yalla-coop/working-class-history/files/7835047/clean.template.xlsx)


**Note**
the columns highlighted with green: these columns must keep as its name currently becuse the code parse data from the CSV file depending on it.

the columns highlighted with yellow: this fields must updated from the baserow table.

the columns highlighted with red: these columns can't find a field to connect with on the baserow table (for this stage maybe in the future)
